name = "boukie-storage"
main = "src/worker.js"
compatibility_date = "2024-11-18"
usage_model = "bundled"

account_id = "132a5735c370d4b7b4d5719d5aec5770"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "my-r2-uploads"
