name = "boukie-storage"
main = "src/worker.js"
compatibility_date = "2024-11-18"
account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "my-r2-uploads"
